#!/bin/bash

if [ -f *.stackdump ]; then
    rm *.stackdump # remove dump files
fi
g++ main.cpp Text.cpp Indexer.cpp -o quickread

result=$?
echo "== g++ returned with status $result =="

exit $result
